### ISSUE TITLE
STM32 HAL Driver Update

### ISSUE THREAD

**Issue by ckilimci** [micropython/stm32lib#11]
Hello all,

Recently, STMicroelectronics updated STM32F4 HAL driver [1]. Some of the APIs are changed, like CAN. Do you plan to update included sources listed here?

[1] https://www.st.com/resource/en/user_manual/dm00105879-description-of-stm32f4-hal-and-ll-drivers-stmicroelectronics.pdf

Sincerely,
Caglar

**Comment by dpgeorge** [comment]
See reply at https://github.com/micropython/micropython/issues/6422

**Comment by ckilimci** [comment]
Thank you very much.
