### ISSUE TITLE
STM32F413 CAN3 support incomplete

### ISSUE THREAD

**Issue by chrismas9** [micropython/stm32lib#5]
@dpgeorge, Micropyhton uses `stm32_hal_legacy.h` definitions for CAN and CAN3 definitions are missing, eg it has `#define __CAN2_CLK_ENABLE __HAL_RCC_CAN2_CLK_ENABLE` but not `#define __CAN3_CLK_ENABLE __HAL_RCC_CAN3_CLK_ENABLE`

There are two ways to fix this. Either update  `stm32_hal_legacy.h` or change MicroPython to directly use the definitions in `stm32f4xx_hal_rcc_ex.h`

Second option means no change to stm32lib. Which do you prefer?

**Comment by chrismas9** [comment]
I have updated can.c to use HAL definitions

**Comment by dpgeorge** [comment]
> I have updated can.c to use HAL definitions

Yes, that's the way I would prefer.
